### ISSUE TITLE
Credentials don't seem to work on demo and I don't receive an OTP code

### ISSUE THREAD

**Issue by bcorvino** [VAIBHAV7500/anime_web_app#20]
Hi,

I was interested to see the project in action and am happy to see you got it staged!  The creds in the README don't seem to work on the app, however.  I attempted to sign up but I never received an OTP code to my email.

Let me know if the creds have changed or if the demo is not meant for outside eyes at this point.

Thank you

**Comment by VAIBHAV7500** [comment]
Hey, 
  Thanks for your interest in the project. Looks like there was some issue from our end. It's resolved now, you can access the website with the mentioned credentials.

Also, we have intentionally blocked the signup feature from our side due to a lot of spam.

Thanks
